### ISSUE TITLE
Generate error when inconsistent blocks are put on the same line in simple mode

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#10]
When inconsistent actions are put together in simple mode, VPL should generate an error. This happens when there are on the same line:
1. two instances of the same action blocks
2. two instances of different blocks using the same actuators, such as the simple and the advanced motor blocks

Point 2. might be solved by #46, but 1. remains.

**Comment by marvelous** [comment]
BlockDefinition.category must be unique if not empty

**Comment by marvelous** [comment]
No, it should not be a predefined list.
