### ISSUE TITLE
A block being dragged to the trash is show below the panes

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#11]

**Comment by marvelous** [comment]
Can't reproduce. Was it in simple mode or advanced mode? Maybe it got fixed accidentally.

**Comment by stephanemagnenat** [comment]
Can't reproduce either. It happened on both simple and advanced mode, now it is fixed in simple mode, and advanced mode is broken.

My guess is that it got fixed accidentally, so I close it now and I'll reopen if the problem appears in advanced mode once fixed.
