### ISSUE TITLE
Duplicate parametrized events on different lines are not detected 

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#113]
If the same set of events with the same parametrization appear on two different lines, this error is not currently detected:
<img width="1072" alt="screen shot 2017-08-03 at 13 36 14" src="https://user-images.githubusercontent.com/390278/28920121-bd2e184a-7850-11e7-95b8-cf1043c8f7e7.png">

In this case, VPL1 shows a red line with linking the two faulty lines:
<img width="795" alt="screen shot 2017-08-03 at 13 43 28" src="https://user-images.githubusercontent.com/390278/28920359-c4fa3206-7851-11e7-87fc-86248149dacd.png">

**Comment by marvelous** [comment]
By default, we'll compare the params value and leave open the possibility for the block to do more exhaustive checks.

**Comment by marvelous** [comment]
As per #116, we should only detect the case where the events are the _same_ (not every possibly overlapping case) _and_ there are conflicting action.
