### ISSUE TITLE
Add a VPL Block to Play Files on Sound Card

### ISSUE THREAD

**Issue by sharon13m** [aseba-community/thymio-vpl2#128]
Currently it is quite complicated for users to play sounds on a sound card - while it is a functionality that users LOVE (of all ages).  This feature should be available in VPL.  I have created a proposed design to add the function into the VPL.  

![image](https://user-images.githubusercontent.com/3308535/34741667-3b7170b2-f538-11e7-9364-5a59e425fc34.png)

Please strongly consider adding so users can make use of the memory card via the VPL.

**Comment by stephanemagnenat** [comment]
Thank you for the input!

Your idea is close to the idea presented in issue #44. The latter also provides the possibility to record a sound from the robot, which I think could be nice for the kids. Do you have an opinion on the usefulness of that ability?

Regarding the design, I have two comments:
- In VPL2, we rather have multiple blocks than blocks with an option, as this allows to target different age groups. In the future, we plan to let the possibility to the teacher to select a set of blocks.
- The list of numbers is not very suited for mobile interaction, but this is a detail.

**Comment by sharon13m** [comment]
I do like the idea to be able to have the ability for users to be able to record sounds.  I do know that recorded sounds on thymio is saved with a different prefix than the playing of a sound that is already on the robot, so I'm not sure yet how you'd cleanly design that.  I sell my education kit with a sound card and a list of files they can download and use.  So I see the recorded and playing of the recorded sound as an interesting possibility, but the design would need to be thought out.  

What do you mean... VPL2?  Is this something new?   I thought I had the most recent Aseba 1.6, and you use the block with an additional option, so that is why I designed it like that to keep the consistency.  Is there a way I can see what you are talking about?  I think you are referencing something that the Scratch design has, I think the current scratch options of blocks are a bit confusing.  Hopefully you have a cleaner design in mind. 

I do like your sounds recorder and I made it into a project here: https://www.techykids.com/voice-recorder-thymio/  

Being able to record the sound straight to the robot would be a great feature.  

Being able to play the sounds that are already on the sound card ... and the sound that has been recorded on the robot would be great.

I'd be interested to see what you are thinking in terms of design.

**Comment by stephanemagnenat** [comment]
> So I see the recorded and playing of the recorded sound as an interesting possibility, but the design would need to be thought out.

Yes. Currently in firmware 11 it is only possible to get the duration of a recorded sound (file `Rx,wav`, can also be put from the computer), so we would start from here.

> What do you mean... VPL2? Is this something new?

We are working on a mobile version, VPL2 is an internal name. It is also the name of this repository (that is why I thought you knew).

Of course aiming at tablet and phones there are pointing precision constraints, which call for new block designs. Note that you can already try a preview version on Android (see https://play.google.com/apps/testing/org.mobsya.thymiovpl2), eventually iOS will be supported as well. The details on how this will translate to desktop are still under discussion.

> Being able to record the sound straight to the robot would be a great feature. Being able to play the sounds that are already on the sound card ... and the sound that has been recorded on the robot would be great.

Yes, I think so too.

> I'd be interested to see what you are thinking in terms of design.

I'll try to come with a mockup soon.

**Comment by stephanemagnenat** [comment]
As promised, I added a mockup in issue #44. Let us continue the discussion there.
