### ISSUE TITLE
Scroll in simple mode should always keep something on screen

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#13]
Currently, in simple mode, the user can scroll the blocks outside the view. This is prone to loose the blocks, and is useless. The blocks should not be able to be scrolled farther away then the margin, meaning that margins apart, there should not be areas on the screen with no blocks.

**Comment by marvelous** [comment]
Why not in advanced mode too?

**Comment by stephanemagnenat** [comment]
In principle this should also apply in advanced mode, but there you might want to scroll the visible blocks partially outside the screen as you might want to make space to drop a new block.

**Comment by marvelous** [comment]
Fix from #14
