### ISSUE TITLE
When an event is dropped, lines is resized but the zoom level is unchanged

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#14]
This leads to the new drop position to be outside view, even when starting from a zoom where everything is visible initially. A way to solve that is to zoom out by the ratio of how much the line was extended, and move the view by the size of the line extension.

**Comment by marvelous** [comment]
I suggest recentering the view instead of changing the zoom. It looks less surprising.

**Comment by stephanemagnenat** [comment]
I am not sure. In VPL1, the automatic resizing of the zoom to fit and centre the blocks on the x-axis worked well, no-one complained ever about that.

But of course VPL2 is in a different platform, and the interaction patterns people might expect are different. I also feel that the constant resize is not very Google Materialish, but neither is the content getting out of screen on both axes. All lists in Material scroll only in one dimension, and arguably VPL2 simple mode is a list.

Reading Material's Responsive UI guidelines on how to adapt elements to different screen sizes (https://material.google.com/layout/responsive-ui.html#responsive-ui-grid), we see that _Element width grows as screen size changes_ is an option. However the guidelines considers a screen size change, while we have a number of elements change.

After thinking, maybe the most Materialish approach would be to actually put all the drop spots for the maximum number of actions, and adapt the zoom level in function of the size of the screen and this maximum (which depends on what actions are shown), and never zoom the UI in simple mode. This would also allow to remove the centre button, and rather we could have a button allowing to see the line with the error, as in VPL1.

What do you think?

**Comment by marvelous** [comment]
After our discussion I had to implement an automatic zoom-out anyway. Event with a limit in the amount of actions, the window could be resized to limit horizontal space.
