### ISSUE TITLE
Complete motor block

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#18]
The motor block currently does not show animation of the robot moving, while it was doing it in VPL1. Without it the understanding of the sliders is worst than in VPL1.

**Comment by stephanemagnenat** [comment]
working on it

**Comment by stephanemagnenat** [comment]
Done in commit 311149df62cd88de9ec087165613fe218ef52846.

**Comment by marvelous** [comment]
Awesome effect!
