### ISSUE TITLE
Simple mode: event without action is valid, should it be?

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#20]
Currently an event without an action is valid in simple mode, while it was forbidden in VPL1. The reason being that it does not make sense, so the user should be encouraged not to do it.

I think that from an educational view, and to have a symmetry with actions, it is helpful to produce an error.

**Comment by stephanemagnenat** [comment]
This should be invalid but an invitation to add a block.

**Comment by marvelous** [comment]
Fixed with #75
