### ISSUE TITLE
Generated code in simple mode cannot follow line as VPL1 does

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#26]
The following program in VPL1 works perfectly, both in simulation and in the real robot:

![vpl1-line-following](https://cloud.githubusercontent.com/assets/390278/21146758/181e0388-c153-11e6-9eac-d51e0b83697c.png)

The corresponding code being:
```
onevent prox
	when prox.ground.delta[0] <= 400 and prox.ground.delta[1] <= 400 do
		motor.left.target = 200
		motor.right.target = 200
		emit pair_run 0
	end
	when prox.ground.delta[0] >= 450 and prox.ground.delta[1] <= 400 do
		motor.left.target = 200
		motor.right.target = 0
		emit pair_run 1
	end
	when prox.ground.delta[0] <= 400 and prox.ground.delta[1] >= 450 do
		motor.left.target = 0
		motor.right.target = 200
		emit pair_run 2
	end
```

However, the corresponding code in VPL2:

![vpl2-line-following](https://cloud.githubusercontent.com/assets/390278/21147041/f54c3310-c153-11e6-9994-4a34ffd05e64.png)

easily losses the track.

From the behaviour of the robot, it seems that the sensors are under-sampled, although the tests are made in the `onevent prox` handler.

**Comment by marvelous** [comment]
Generated code
[26.txt](https://github.com/aseba-community/thymio-vpl2/files/649659/26.txt)

**Comment by stephanemagnenat** [comment]
The bug is in the generated `return` statements if a transition is taken, the first being in line 127. It is a problem because the transitions for the other threads are not tested, and therefore they cannot be re-initilaized.

A solution to this problem is to put the test of the transitions in a subroutine.

**Comment by stephanemagnenat** [comment]
With this code, the robot works correctly and never gets out of the track.
