### ISSUE TITLE
StartIndicator should not be "inside" the Block 

### ISSUE THREAD

**Issue by marvelous** [aseba-community/thymio-vpl2#32]
They should be separate.

In simple mode, the start indicator should not move when dragging the event block; the invisible link from the last non-empty action of the row should point to the start indicator state (proper fix for #9).

In advanced mode, the user should not be able to create such link.

**Comment by stephanemagnenat** [comment]
Just to keep track, following our last discussion, there should not be anymore StartIndicator in simple/reactive mode. This is related to issue #35.
