### ISSUE TITLE
Action execution is not shown any more

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#33]
While 95f0000624698f8001591c84498d4c13ad3c9997 corrected #9, it seems it introduced another bug: now the action executed is never highlighted in simple mode.

**Comment by marvelous** [comment]
Ouch! The proper fix will require something closer to #32

**Comment by stephanemagnenat** [comment]
As discussed by phone, for the simple mode the easiest is to blink the whole events-actions pair, as they all happen concurrently.
