### ISSUE TITLE
Display bug in simple mode when a program is loaded

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#34]
When a program is loaded, an empty event-action pair is displayed on top of the others in the list. See this screenshot:

![simple-mode-display-bug-load](https://cloud.githubusercontent.com/assets/390278/21277351/3653d8ca-c3d6-11e6-9901-564c95908bca.png)

**Comment by marvelous** [comment]
Can't reproduce. What did you do previously? Can you send me the code (console.log in Editor.qml::loadCode)? I am still on Qt 5.7.0

**Comment by stephanemagnenat** [comment]
I also cannot reproduce on my laptop, with either master or remy, using Qt5.7.1. I'll try to collect more information when this bug appears. Maybe a specific saved state is broken.
