### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by marvelous** [aseba-community/thymio-vpl2#35]

**Comment by stephanemagnenat** [comment]
A minimal cleanup should be done, to allow for an agile development of VPL Mobile Preview.

This cleanup should contain:
- Short readme file (@stephanemagnenat)
- Cleaned-up compiler with short documentation of the interfaces (@marvelous)

**Comment by stephanemagnenat** [comment]
I'm working on the short readme file, and I realise that our source tree is not very clean:
- There are a lot of source files at the top level. It is probably cleaner to have them in a sub-directory, excepted maybe the top-level application file. Ideally, everything that is part of thymio-vpl2.pri should be in a sub-directory.
- There are images sub-directories in different directories. Although initially it felt like a good idea, I now think that it is not, and would rather put everything into an `assets` directory, with sub-directories for the different types of assets (icons, etc.)

@marvelous what do you think?

**Comment by stephanemagnenat** [comment]
Commit 4aff83ff34b2273b5228c5107c25dc9512a37e3c adds the short readme file. Once we have restructured the source tree, this file should be updated with an overview of the directories, like [the one in Aseba](/aseba/blob/master/readme.sourcetree.md).

**Comment by stephanemagnenat** [comment]
It would be good to think about durative actions (#69) when refactoring the compiler, even if we do not implement them right away.

**Comment by marvelous** [comment]
Moved compiler stuff to #70 and #71

**Comment by marvelous** [comment]
- images sub-directories in different directories: I don't like ordering files by type at all. I prefer to have images in the same directory as the qml file that uses them.

- source files at the top level: it's again about ordering files by type, although I agree that we have too many at the top level

**Comment by marvelous** [comment]
#96 tracks what remains
