### ISSUE TITLE
Dragging blocks from side bars tends to scroll them

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#6]
Currently because we have a ListView to hold block icons on side bars, dragging a block tend to scroll the sideview if the block is not dragged perpendicularly to the border, which happens with most users.

**Comment by stephanemagnenat** [comment]
I've reviewed the Google Material guidelines and did not find an obvious solution. I think that we will have to implement our own behaviour, for instance:
- when a drag is started, analysing the direction
- if the drag is vertical and more than a threshold, initialise a scroll of the pane
- if the drag is towards the center area and more than a threshold, initialise a drag block into the area
- once a decision is taken, stick to it until the drag is cancelled.

**Comment by mbonani** [comment]
Actually it seems that if you go horizontal it works and made correctly the drag and drop and if there is small composante vertical it make scroll the bar. 
Couldn't just inverse that? If there is a horizontal component make the drag and drop and scroll only if vertical. 
Basically it is what you describe, but I can also propose another behaviour:
For me, if you take the center of a block element it should drag and drop. 
When you whant to scroll you click between the element. That is perhaps more simple to implement...

**Comment by stephanemagnenat** [comment]
The problem is that the drag behaviour is currently not under our control because we compose two Qt widgets. We should hack them to get back the control.

I am not sure about having a different behaviour in function of where you click, as this seems far from what people expect in touch-based interface, but it is hard to say without testing. Implementation-wise, it won't be easier.

**Comment by marvelous** [comment]
Scrolling disabled for now, to lower the priority of this bug
