### ISSUE TITLE
document compiler internals and interface

### ISSUE THREAD

**Issue by marvelous** [aseba-community/thymio-vpl2#71]

**Comment by stephanemagnenat** [comment]
Some elements useful to have in this document would be:
- General idea of what state, thread, transition mean in this context.
- The limitations in term of number of possible transitions, etc.
- Whether states are per thread or global.
- What happens with durative actions (for instance timer). Is timer the only element implemented or is the implementation generic (can we have a "move 20 cm" action, provided the robot's odometry is calibrated).
- The general idea of the compiler architecture.

**Comment by marvelous** [comment]
I commited a first draft, which does not yet address all your points.
