### ISSUE TITLE
Stop the program when it is modified

### ISSUE THREAD

**Issue by mbonani** [aseba-community/thymio-vpl2#77]
In VPL1 you can modify the program and let the robot continue. 
It is only when you press stop that its stop. 
Here in VPL2 when you modify it stop directly the execution. I am not convinced by the feature.

**Comment by stephanemagnenat** [comment]
> Here in VPL2 when you modify it stop directly the execution. I am not convinced by the feature.

It is a good point, we need more testing, I will keep this in mind during the workshops this week.

**Comment by stephanemagnenat** [comment]
After discussion with @mbonani and @cbarraud, we agreed, until further evidence, that the current behaviour of stopping the program when it is modified, is sound.
