### ISSUE TITLE
Visual artefact on block panes scroll

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#79]
When one scrolls the block panes, sometimes an artifact appears.

This bug can be reproduced by clicking in-between two blocks, and scrolling up and down the pane with the mouse on a computer.

**Comment by marvelous** [comment]
Looks like a QT bug? mouse.y randomly reports a negative value in the positionChanged signal when scrolling quickly up and down.

Or maybe this would not happen if we used a MouseArea over the whole ListView instead of one MouseArea over each Block

**Comment by stephanemagnenat** [comment]
Can we make a quick workaround (filtering unrealistic value changes?) and build a minimal test case to submit as a bug report to Qt?

**Comment by marvelous** [comment]
It looks like the negative values were not effecting this visual glitch, it was the second hypothesis: when the mouse cursor was outside the grabbed block, the list would return to its bounds.
