### ISSUE TITLE
Inconsistent program start in simple mode

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#8]
It seems that in simple mode, sometimes, the program does not start.

I can create such a situation by making a simple program to follow a black line on the ground using 4 pairs of ground-sensor (each one with a different configuration of black/white) and simple motor block. When I put the robot on the track and then start the program, sometimes the robot does not move. If I take the robot away from the track and move my hand in front of the ground sensors, the robot starts moving, and then the program works correctly.

**Comment by mbonani** [comment]
This is perhaps link to firmware issue (https://github.com/aseba-community/aseba-target-thymio2/issues/16)

**Comment by stephanemagnenat** [comment]
No it happens with the simulator as well.

But I think it is corrected now, @marvelous can you confirm?

**Comment by marvelous** [comment]
Is it a dupe of #23? I can't confirm whether you still have the issue or not...

**Comment by stephanemagnenat** [comment]
Yes it is a dup of #23, therefore corrected, closing.
